### ISSUE TITLE
Missing "Outcome 10"

### ISSUE THREAD

**Issue by mikesnowkettering** [CDCgov/covid19healthbot#10]
There is a missing "Outcome 10" before a "MSG 10" block on the right side of the core scenario.  Here's a picture.  I fixed this in our copy by simply cloning the other existing "Outcome 10" block and adding it just before this "MSG 10".
![image](https://user-images.githubusercontent.com/62905400/78450225-27c3f580-764b-11ea-8f8b-0faeac3c716c.png)

**Comment by kmuterspaw** [comment]
Thanks for letting us know. We'll be sure to fix this in the next push.

**Comment by kmuterspaw** [comment]
Fixed in the latest push. Please let us know if you find other issues.
