### ISSUE TITLE
Virginia Department of Health URL is Incorrect

### ISSUE THREAD

**Issue by pjhill** [CDCgov/covid19healthbot#12]
## Description
At the end of the symptom checker the "Sorry you're feeling sick" chat appears to contain an incorrect link to Virginia Department of Health.

## Expected
Virginia Department of Health link sends the user to (http://www.vdh.virginia.gov/)

## Actual
Virginia Department of Health link sends the user to (http://www.vdh.state.va.us/)

## Example Screen shot
![image](https://user-images.githubusercontent.com/52456633/80131349-185c0c00-8568-11ea-943c-1e48b20433dc.png)

**Comment by kmuterspaw** [comment]
Thanks for letting us know! This is fixed in the latest version.
