### ISSUE TITLE
Arkansas Department of Health URL is Incorrect

### ISSUE THREAD

**Issue by pjhill** [CDCgov/covid19healthbot#13]
## Description
At the end of the symptom checker the "Sorry you're feeling sick" chat appears to contain an incorrect link to Arkansas Department of Health.

## Expected
Arkansas Department of Health link sends the user to the Arkansas Department of Health's page.

## Actual
Arkansas Department of Health link sends the user to an error page.

## Example Screen shot
![image](https://user-images.githubusercontent.com/52456633/80139673-d4233880-8574-11ea-9993-ccadf50a5149.png)

**Comment by pjhill** [comment]
The correct URL may be -- (https://www.healthy.arkansas.gov/)

**Comment by kmuterspaw** [comment]
Thanks for letting us know! This is fixed in the latest version.
