### ISSUE TITLE
Rhode Island Department of Health URL is incorrect

### ISSUE THREAD

**Issue by pjhill** [CDCgov/covid19healthbot#14]
## Description
At the end of the symptom checker the "Sorry you're feeling sick" chat appears to contain an incorrect link to Rhode Island Department of Health.

## Expected
Rhode Island Department of Health link sends the user to the Rhode Island Department of Health's page.

## Actual
Rhode Island Department of Health link sends the user to an unreachable page (http://www.health.state.ri.gov/).

## Example Screen shot
![image](https://user-images.githubusercontent.com/52456633/80139969-4b58cc80-8575-11ea-88b8-75817128f5b2.png)

**Comment by pjhill** [comment]
The correct URL may be -- (https://health.ri.gov/)

**Comment by kmuterspaw** [comment]
Thanks for letting us know! This is fixed in the latest version.
