### ISSUE TITLE
Multisystem Inflammatory Syndrome in Children (MIS-C) 

### ISSUE THREAD

**Issue by mikesnowkettering** [CDCgov/covid19healthbot#15]
Are there plans to include modifications to the core algorithm to account for the guidance that has been released around [Multisystem Inflammatory Syndrome in Children (MIS-C)](https://emergency.cdc.gov/han/2020/han00432.asp)?

**Comment by tomsavel** [comment]
Hi!  Thanks for the comment.  Regarding your MIS-C question: No plans...not at this time.  Thanks!

**Comment by mikesnowkettering** [comment]
Thanks for the response, @tomsavel .
