### ISSUE TITLE
Documentation for Implementation

### ISSUE THREAD

**Issue by dpretlornasa** [CDCgov/covid19healthbot#38]
Hello, is there any documentation for implementing this within our own website? We don't want to just embed, we want to be able to collect the output. Any assistance would be greatly appreciated.

**Comment by pwhitebe** [comment]
Greetings,

The three [screening protocol JSON bot files](https://github.com/CDCgov/covid19healthbot/tree/master/screening_protocols/latest) (Wrapper, Core, and Pediatric Core) and the [localization file](https://github.com/CDCgov/covid19healthbot/blob/master/screening_protocols/localization-custom-strings.xlsx) are designed to be quickly imported into the Microsoft Azure Health Bot which is part of the [Microsoft Bot Framework](https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0).  The bot can then interact with your website via [configurable channels](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0) The usage/selection data is also generated into a javascript [output block](https://github.com/CDCgov/covid19healthbot/wiki) which details what options a user chose and which message(s) they were shown which can be used for reporting.
