### ISSUE TITLE
CDC Widget Down 

### ISSUE THREAD

**Issue by JustAnotherMexa** [CDCgov/covid19healthbot#45]
The Widget has stopped working for the last week or so. 
It's showing a Uncaught ReferenceError: protocol is not defined, this can be seen on the cdc website as well: 
https://tools.cdc.gov/medialibrary/index.aspx#/media/id/405848

**Comment by bph9** [comment]
Thanks for letting us know. We are working on getting this fixed.

**Comment by bph9** [comment]
This has been fixed.

**Comment by JustAnotherMexa** [comment]
Thanks for the quick turn around
