### ISSUE TITLE
Are Determinations Made on Phone Fingerprinting?

### ISSUE THREAD

**Issue by soyfrien** [CDCgov/covid19healthbot#57]
I was looking through the algorithm flow charts and did not find this, however when I was told that I had been exposed to someone I don't know how it determined that with the information I supplied.

Mainly I said I was feeling sick > conditions improving > don't know if I was exposed > not tested in last ten days > tested negative in last 1 to 3 months.

I am enrolled in my State's exposure tracking program but the State app or the iPhone didn't alert me.

Does the CDC survey know or is it playing it safe?

**Comment by bph9** [comment]
When you answer "I don't know", the algorithm follows the same path as if you had answered "Yes". I takes the cautious approach and plays it safe. If you are enrolled in your State's exposure tracking program, the bot does not know this. The bot does not know who you are.

**Comment by soyfrien** [comment]
Thank you, @bph9.
