### ISSUE TITLE
Post-exposure prophylaxis content

### ISSUE THREAD

**Issue by henryweimd** [CDCgov/covid19healthbot#67]
Post-exposure content does not appear to mention, link to or advise high-risk patients to discuss prophylaxis (prevention) mentioned in current NIH guidelines and recent FDA updated EUA.  

E.g. post-exposure prophylaxis
https://www.covid19treatmentguidelines.nih.gov/therapies/anti-sars-cov-2-antibody-products/anti-sars-cov-2-monoclonal-antibodies/

CDC (the centers for disease control and prevention) existing public-facing verbiage about this type of prevention here:
https://www.cdc.gov/coronavirus/2019-ncov/your-health/treatments-for-severe-illness.html

“For people at high risk of disease progression. 
“The FDA has issued EUAs for a number of  investigational monoclonal antibodies that can attach to parts of the virus. These antibodies could help the immune system recognize and respond more effectively to the virus. The NIH COVID-19 Treatment Guidelinesexternal icon provide information about these drugs and describe what is known about their effectiveness. If used, they should be administered as soon as possible after diagnosis and within 10 days of symptom onset. Your healthcare provider will decide whether these investigational treatments are appropriate to treat your illness.”

CDC publishes content on other post exposure prophylaxis for other conditions;  precedent references:
https://www.cdc.gov/hiv/risk/pep/index.html
https://www.cdc.gov/hepatitis/hbv/pep.htm

**Comment by bph9** [comment]
Thank you for this information. I will run this by our team and see how they would like to handle this.

**Comment by bph9** [comment]
We reviewed the links you sent and are going to look into including the one from the CDC about treatments a provider might recommend. This will need to be reviewed by our clinical team before it can be added. If approved, we will work on adding it to the next update.  

Thanks.

**Comment by henryweimd** [comment]
Thank you.  Could you kindly revisit this issue with the clinical team?   It may be prudent to prompt, specifically, high-risk users to discuss general categories of post-exposure options with their healthcare provider immediately.  It is probably not feasible to add messaging about specific options, though.

The current guidance given in the algorithm may be misleading and potentially harm users e.g. those who are immunocompromised, unless it includes guidance to discuss post-exposure prophylaxis and/or even treatment (as they emerge under EUA) with their healthcare providers.  The language around influenza ("consider asking your provider") may be appropriate for COVID itself.  

The bot otherwise currently makes reference to therapeutics for influenza and acetaminophen and "over the counter" remedies.

For example, for an 84 year-old Black man with positive test, symptoms, and cancer history, currently the algorithm leads to:

1. (therapeutic recommendation only for over-the-counter medicines)
"Get rest and stay hydrated. Take over-the-counter medicines, such as acetaminophen, if needed to help you feel better."

and
2. (prompt to discuss testing or treatment with healthcare provider)
"Because some of the symptoms of flu and COVID-19 are similar, you may want to consider asking your provider about testing or treatment for influenza."

As oral and injectable prophylaxis and therapeutics are reviewed for EUA, and then ongoing variant-related adjustments are made to guidance, it is unlikely that specific guidance will be feasible.  But it may help protect more people to prompt them to a) immediately discuss these possibilities with their healthcare provider, given the limited time to act for most regimens from time of symptom onset and/or positive test results, and to also b) point out that this landscape is rapidly-evolving.

Potential wording might be patterned after the "you may want to consider asking your provider about" clause in the influenza guidance there right now:
CURRENT: "Call your medical provider, clinician advice line, or telemedicine provider as soon as possible."
POTENTIAL UPDATE: "Call your medical provider, clinician advice line, or telemedicine provider as soon as possible.  You may want to consider asking your provider about medicines that can be given to prevent or treat an infection."

Thanks so much again.
