### ISSUE TITLE
Theme7 does not work

### ISSUE THREAD

**Issue by Thando-James** [CDCgov/covid19healthbot#69]
I embedded the custom button theme in my nextjs project and it did not work. Nothing happens after you click the button.

**Comment by bph9** [comment]
Is theme7 the only one that does not work or do they all not work?

**Comment by pwhitebe** [comment]
The script that the themes reference are rather heavy and are probably going to conflict with some of the elements of nextjs.  Thus, the button will probably need to be buffered into it's own content-area or placed in a more simple HTML page and then referenced into the project.

**Comment by Thando-James** [comment]
Theme 7 is the only theme not working

**Comment by Thando-James** [comment]
Okay i will try that
