### ISSUE TITLE
Question about "completion_event" usage

### ISSUE THREAD

**Issue by mikesnowkettering** [CDCgov/covid19healthbot#7]
Thank you so much for creating this repo and providing such excellent documentation by way of the questions, care advice messages, and algorithm flowchart.  You are awesome, and this was timely.

My question is about keeping the algorithm "pure".  I've noticed that all of the "MSG x" exit points for the covid19_core scenario have Message Metadata that looks like this (example):

`{
 name: "completion_event",
 message_id: 8   
}`

This seems like it would be useful to return the message_id value to a wrapper scenario so that additional workflow after the algorithm completes can be customized based upon the output of the algorithm.  However, I can't see where this value is ever being returned and it doesn't show up in the Watch as a variable.  I'm probably showing my ignorance of the tool but I was wondering how you are using this variable and if it is accessible anywhere.  I think I'm probably overlooking something simple.  

I did see where I can customize the messages with additional content in the Custom MSG action block, but I would like to create HeroCards with clickable links so I would rather handle that in the wrapper vs. the covid19_core scenario.  This would also allow for me to simply update the covid19_core scenario from this respository as it is updated and keep any customizations in the wrapper scenerio. 

Any direction you can give about keeping customizations out of the core scenario and being able to know what MSG was displayed to the guest as a return value would be appreciated.

**Comment by tomsavel** [comment]
Thanks very much for your questions! 

To answer your first question, the message metadata that you mentioned is used solely on the client in the WebChat UI. The client subscribes to these completion events and that information is used for analytics. If you are interested in a code snippet on how to subscribe to these events on the client, we are happy to provide that for you.

Regarding your second question, we are still looking into the best way this would be possible. We understand that you want to keep that core protocol pure and avoid customizations. As we learn more, we’ll provide you with more feedback. Additionally, this functionality is something we may implement in the core protocol in the future, and if we do, we’ll be sure to inform you.

**Comment by mikesnowkettering** [comment]
Thank you for the response, @tomsavel .  Yes, I would be interested in a code snippet for subscribing to those completion events.  That would definitely be useful for analytics.

Based upon your answer to the second question, we will proceed with utilizing the core protocol scenerio for those outside of our region and then customize a cloned scenario, via the mechanism that you have already provided for, that includes our localized care advice message adjustments.  I will definitely be watching for updates that allow this to happen more programmatically.

Thank you again for helping to publish this information in this repo.  It couldn't have come at a better time for us.

**Comment by mikesnowkettering** [comment]
The first commit from earlier today resolved this issue nicely.  I like the ability to turn on or off the core scenerios messages and then also receive the message ids in a conversation level variable.  Very nicely done.
