### ISSUE TITLE
Potential issue in wrapper scenario's call to the core scenario

### ISSUE THREAD

**Issue by mikesnowkettering** [CDCgov/covid19healthbot#8]
I was copying and pasting the code that creates the scenarioArgs variables, that are passed from the wrapper to the core scenario, so that I would ensure I was getting the right variable names used by the core scenario in our custom wrapper.  Currently these variables are passed in the begin scenario block as follows:

`{
custom_outcome_message: scenario.state_msg,
show_core_message: true
}`

However, when I changed show_core_message to be false it did not change the behavior.  I then realized that the variable names in the "Arguments (to pass to the scenario):" box needed to be enclosed as quotes since they are the name of the variable.  I changed it to this and it worked correctly (true or false):

`{
"custom_outcome_message": null,
"show_core_message": true
}
`

**Comment by kmuterspaw** [comment]
We are not facing this issue on our side. We are able to pass the scenario arguments without making the property names strings. Could you provide more information about the problem you were seeing? Did it happen only during a specific path?

**Comment by mikesnowkettering** [comment]
It was happening for all paths.  I'm glad it is working in your environment.  It is not in mine, but I was able to discover it and fix it.  I'm wondering if there is a different code base at the Health Bot environment level.  Here are some more details with pictures to give better clarity as to the issue.

When using this code...
`{
custom_outcome_message: scenario.state_msg,
show_core_message: true
}
`
...it produces the following output in the Watch:
![image](https://user-images.githubusercontent.com/62905400/78450290-9acd6c00-764b-11ea-9711-43b0b270562b.png)

When using this code...
`{
"custom_outcome_message": null,
"show_core_message": true
}
`
...it produces the following output in the Watch:
![image](https://user-images.githubusercontent.com/62905400/78450306-b9336780-764b-11ea-9ec8-f11df405ed5e.png)

You can see that one is passing in the whole code block as a string and the other is passing in appropriately defined variables.

**Comment by kmuterspaw** [comment]
Could you pull the latest and see if you are still having this issue? If it's still an issue, we can reach out to Microsoft and see if they can provide any insight.

**Comment by mikesnowkettering** [comment]
Seems to be working in the current build without making the variable names a string.  I can't explain the previous behavior because nothing else should have changed.  It was consistent but now I cannot reproduce the problem.  Closing out this issue.
![image](https://user-images.githubusercontent.com/62905400/78996311-4f670200-7b12-11ea-81c8-7812260a3dea.png)
